name: Packer

on:
  push:
    branches:
        - 'main'

permissions:
 id-token: write
 contents: read          

jobs:
  packer:
    runs-on: ubuntu-latest
    name: Packer

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # AWS Credentials Setup (Magic)
  
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::1000000000:role/Packer_deploy_role # Add the role created by the terraform setup
          aws-region: eu-west-2

      - name: Set Working Directory
        run: cd Packer/
        working-directory: Packer/

      # fix backwards incompatibilities in template
      - name: Initialise Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: init

      # validate templates
      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: build.pkr.hcl

      # build artifact
      - name: Build Artifact
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: "-color=false -on-error=abort"
          target: .
          working_directory: .
        env:
          PACKER_LOG: 1